constraint_setting(name = "cpu_variant")

constraint_value(
    name = "cortex_m0",
    constraint_setting = ":cpu_variant",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "cortex_m1",
    constraint_setting = ":cpu_variant",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "cortex_m3",
    constraint_setting = ":cpu_variant",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "cortex_m4",
    constraint_setting = ":cpu_variant",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "cortex_m4f",
    constraint_setting = ":cpu_variant",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "none",
    constraint_setting = ":cpu_variant",
    visibility = ["//visibility:public"],
)